# Generated by Django 3.2.9 on 2021-11-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('rate_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('aval', 'aval'), ('rent', 'rent'), ('sol', 'sol')], max_length=50, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lmsapp.category')),
            ],
        ),
    ]
