# Generated by Django 3.2.9 on 2021-11-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_auto_20211112_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
